version: '3'
services:
#  zookeeper:
#    image: bitnami/zookeeper
#    container_name: zookeeper
#    environment:
#      - ZOO_SERVER_ID=1
#      - ZOO_SERVERS=0.0.0.0:2888:3888
#      - ALLOW_ANONYMOUS_LOGIN=yes
#    networks:
#      - kafka_consumer_network
#  kafka:
#    image: bitnami/kafka
#    container_name: kafka_consumer
#    ports:
#      - "9092:9092"
#    networks:
#      - kafka_consumer_network
#    environment:
#      - KAFKA_BROKER_ID=1
#      - ALLOW_PLAINTEXT_LISTENER=yes
#      - KAFKA_CFG_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092
#      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://localhost:9092
#      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  consumer:
    build: .
    image: consumer:latest
    container_name: consumer
#    depends_on:
#      - kafka
    networks:
      - kafka_network

  mysql:
    # *-----------------------------*
    # To connect to the DB:
    #   docker exec -it mysql bash -c 'mysql -u root -p$MYSQL_ROOT_PASSWORD'
    # *-----------------------------*
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=fowu_user
      - MYSQL_PASSWORD=1234
    volumes:
      - ${PWD}/data/mysql:/docker-entrypoint-initdb.d
      - ${PWD}/data:/data
    networks:
      - kafka_network

networks:
  kafka_network:
    name: kafka_network
    external: true
