{
 "title": "FOWU",
 "time": { "from": "now-10m", "to": "now" },
 "panels": [
  {
   "title": "Wind Direction",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "dataset": "fowudatabase",
     "rawSql": "SELECT \n  CAST(captureTime AS int) AS \"time\",\n  windDirection \nFROM fowudatabase.dbo.weather"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "dataset": "fowudatabase",
     "rawSql": "SELECT \n  CAST(captureTime AS int) AS \"time\",\n  CAST(windSpeed AS DOUBLE PRECISION)\nFROM fowudatabase.dbo.weather"
    }
   ]
  },
  {
   "title": "Wave Direction",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "SELECT \n  CAST(captureTime AS int) AS \"time\",\n  waveDirection \nFROM fowudatabase.dbo.weather"
    }
   ]
  },
  {
   "title": "Wave Period",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT \n  CAST(captureTime AS int) AS \"time\",\n  CAST(wavePeriod AS DOUBLE PRECISION)\nFROM fowudatabase.dbo.weather"
    }
   ]
  },
  {
   "title": "Wave Height",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "rawSql": "SELECT \n  CAST(captureTime AS int) AS \"time\",\n  CAST(waveHeight AS DOUBLE PRECISION)\nFROM fowudatabase.dbo.weather"
    }
   ]
  }
 ]
}