{
 "title": "FOWU",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Wind Direction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "SELECT\n  captureTime AS \"time\",\n  windDirection\nFROM weather\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  captureTime AS \"time\",\n  windSpeed\nFROM weather\nORDER BY captureTime"
    }
   ]
  },
  {
   "title": "Wave Direction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "SELECT\n  captureTime AS \"time\",\n  waveDirection\nFROM weather\nORDER BY captureTime"
    }
   ]
  },
  {
   "title": "Wave Period",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  captureTime AS \"time\",\n  wavePeriod\nFROM weather\nORDER BY captureTime"
    }
   ]
  },
  {
   "title": "Wave Height",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  captureTime AS \"time\",\n  waveHeight\nFROM weather\nORDER BY captureTime"
    }
   ]
  }
 ]
}